packages:
  - apps/*
  - infra/*
  - libs/*
  - packages/*
  - scripts/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@pulumi/kubernetes'
  - esbuild
  - msgpackr-extract
  - protobufjs
  - sharp
  - unrs-resolver
