import type { Metadata } from "next"
import { Fira_Mono, Fira_Sans } from "next/font/google"
import "./globals.css"
import type { PropsWithChildren } from "react"
import { Body } from "~/ui/components/root/Body"

const firaSans = Fira_Sans({
  variable: "--font-fira-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"]
})

const firaMono = Fira_Mono({
  variable: "--font-fira-mono",
  subsets: ["latin"],
  weight: ["400", "500"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" className={`${firaSans.variable} ${firaMono.variable}`}>
      <Body>
        {children}
      </Body>
    </html>
  )
}
