/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as healthLivezRouteImport } from './routes/(health)/livez'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthedAdminRouteRouteImport } from './routes/_authed/admin/route'
import { Route as AuthedAppRouteRouteImport } from './routes/_authed/_app/route'
import { Route as authSignInCallbackRouteImport } from './routes/(auth)/sign-in.callback'
import { Route as AuthedAdminFramedRouteRouteImport } from './routes/_authed/admin/_framed/route'
import { Route as AuthedAppFramedRouteRouteImport } from './routes/_authed/_app/_framed/route'
import { Route as AuthedAdminFramedIndexRouteImport } from './routes/_authed/admin/_framed/index'
import { Route as AuthedAppFramedWsWorkspaceIdRouteImport } from './routes/_authed/_app/_framed/ws/$workspaceId'
import { Route as AuthedAppFramedUUserIdRouteImport } from './routes/_authed/_app/_framed/u/$userId'

const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const healthLivezRoute = healthLivezRouteImport.update({
  id: '/(health)/livez',
  path: '/livez',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminRouteRoute = AuthedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAppRouteRoute = AuthedAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const authSignInCallbackRoute = authSignInCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => authSignInRoute,
} as any)
const AuthedAdminFramedRouteRoute = AuthedAdminFramedRouteRouteImport.update({
  id: '/_framed',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAppFramedRouteRoute = AuthedAppFramedRouteRouteImport.update({
  id: '/_framed',
  getParentRoute: () => AuthedAppRouteRoute,
} as any)
const AuthedAdminFramedIndexRoute = AuthedAdminFramedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminFramedRouteRoute,
} as any)
const AuthedAppFramedWsWorkspaceIdRoute =
  AuthedAppFramedWsWorkspaceIdRouteImport.update({
    id: '/ws/$workspaceId',
    path: '/ws/$workspaceId',
    getParentRoute: () => AuthedAppFramedRouteRoute,
  } as any)
const AuthedAppFramedUUserIdRoute = AuthedAppFramedUUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => AuthedAppFramedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/admin': typeof AuthedAdminRouteRouteWithChildren
  '/sign-in': typeof authSignInRouteWithChildren
  '/livez': typeof healthLivezRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/api/$': typeof ApiSplatRoute
  '/sign-in/callback': typeof authSignInCallbackRoute
  '/admin/': typeof AuthedAdminFramedIndexRoute
  '/u/$userId': typeof AuthedAppFramedUUserIdRoute
  '/ws/$workspaceId': typeof AuthedAppFramedWsWorkspaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/admin': typeof AuthedAdminFramedIndexRoute
  '/sign-in': typeof authSignInRouteWithChildren
  '/livez': typeof healthLivezRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/api/$': typeof ApiSplatRoute
  '/sign-in/callback': typeof authSignInCallbackRoute
  '/u/$userId': typeof AuthedAppFramedUUserIdRoute
  '/ws/$workspaceId': typeof AuthedAppFramedWsWorkspaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/error': typeof ErrorRoute
  '/_authed/_app': typeof AuthedAppRouteRouteWithChildren
  '/_authed/admin': typeof AuthedAdminRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRouteWithChildren
  '/(health)/livez': typeof healthLivezRoute
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/api/$': typeof ApiSplatRoute
  '/_authed/_app/_framed': typeof AuthedAppFramedRouteRouteWithChildren
  '/_authed/admin/_framed': typeof AuthedAdminFramedRouteRouteWithChildren
  '/(auth)/sign-in/callback': typeof authSignInCallbackRoute
  '/_authed/admin/_framed/': typeof AuthedAdminFramedIndexRoute
  '/_authed/_app/_framed/u/$userId': typeof AuthedAppFramedUUserIdRoute
  '/_authed/_app/_framed/ws/$workspaceId': typeof AuthedAppFramedWsWorkspaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/error'
    | '/admin'
    | '/sign-in'
    | '/livez'
    | '/onboarding'
    | '/api/$'
    | '/sign-in/callback'
    | '/admin/'
    | '/u/$userId'
    | '/ws/$workspaceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/error'
    | '/admin'
    | '/sign-in'
    | '/livez'
    | '/onboarding'
    | '/api/$'
    | '/sign-in/callback'
    | '/u/$userId'
    | '/ws/$workspaceId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/error'
    | '/_authed/_app'
    | '/_authed/admin'
    | '/(auth)/sign-in'
    | '/(health)/livez'
    | '/_authed/onboarding'
    | '/api/$'
    | '/_authed/_app/_framed'
    | '/_authed/admin/_framed'
    | '/(auth)/sign-in/callback'
    | '/_authed/admin/_framed/'
    | '/_authed/_app/_framed/u/$userId'
    | '/_authed/_app/_framed/ws/$workspaceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  ErrorRoute: typeof ErrorRoute
  authSignInRoute: typeof authSignInRouteWithChildren
  healthLivezRoute: typeof healthLivezRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/(health)/livez': {
      id: '/(health)/livez'
      path: '/livez'
      fullPath: '/livez'
      preLoaderRoute: typeof healthLivezRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/_app': {
      id: '/_authed/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedAppRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/(auth)/sign-in/callback': {
      id: '/(auth)/sign-in/callback'
      path: '/callback'
      fullPath: '/sign-in/callback'
      preLoaderRoute: typeof authSignInCallbackRouteImport
      parentRoute: typeof authSignInRoute
    }
    '/_authed/admin/_framed': {
      id: '/_authed/admin/_framed'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminFramedRouteRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/_app/_framed': {
      id: '/_authed/_app/_framed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedAppFramedRouteRouteImport
      parentRoute: typeof AuthedAppRouteRoute
    }
    '/_authed/admin/_framed/': {
      id: '/_authed/admin/_framed/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminFramedIndexRouteImport
      parentRoute: typeof AuthedAdminFramedRouteRoute
    }
    '/_authed/_app/_framed/ws/$workspaceId': {
      id: '/_authed/_app/_framed/ws/$workspaceId'
      path: '/ws/$workspaceId'
      fullPath: '/ws/$workspaceId'
      preLoaderRoute: typeof AuthedAppFramedWsWorkspaceIdRouteImport
      parentRoute: typeof AuthedAppFramedRouteRoute
    }
    '/_authed/_app/_framed/u/$userId': {
      id: '/_authed/_app/_framed/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof AuthedAppFramedUUserIdRouteImport
      parentRoute: typeof AuthedAppFramedRouteRoute
    }
  }
}

interface AuthedAppFramedRouteRouteChildren {
  AuthedAppFramedUUserIdRoute: typeof AuthedAppFramedUUserIdRoute
  AuthedAppFramedWsWorkspaceIdRoute: typeof AuthedAppFramedWsWorkspaceIdRoute
}

const AuthedAppFramedRouteRouteChildren: AuthedAppFramedRouteRouteChildren = {
  AuthedAppFramedUUserIdRoute: AuthedAppFramedUUserIdRoute,
  AuthedAppFramedWsWorkspaceIdRoute: AuthedAppFramedWsWorkspaceIdRoute,
}

const AuthedAppFramedRouteRouteWithChildren =
  AuthedAppFramedRouteRoute._addFileChildren(AuthedAppFramedRouteRouteChildren)

interface AuthedAppRouteRouteChildren {
  AuthedAppFramedRouteRoute: typeof AuthedAppFramedRouteRouteWithChildren
}

const AuthedAppRouteRouteChildren: AuthedAppRouteRouteChildren = {
  AuthedAppFramedRouteRoute: AuthedAppFramedRouteRouteWithChildren,
}

const AuthedAppRouteRouteWithChildren = AuthedAppRouteRoute._addFileChildren(
  AuthedAppRouteRouteChildren,
)

interface AuthedAdminFramedRouteRouteChildren {
  AuthedAdminFramedIndexRoute: typeof AuthedAdminFramedIndexRoute
}

const AuthedAdminFramedRouteRouteChildren: AuthedAdminFramedRouteRouteChildren =
  {
    AuthedAdminFramedIndexRoute: AuthedAdminFramedIndexRoute,
  }

const AuthedAdminFramedRouteRouteWithChildren =
  AuthedAdminFramedRouteRoute._addFileChildren(
    AuthedAdminFramedRouteRouteChildren,
  )

interface AuthedAdminRouteRouteChildren {
  AuthedAdminFramedRouteRoute: typeof AuthedAdminFramedRouteRouteWithChildren
}

const AuthedAdminRouteRouteChildren: AuthedAdminRouteRouteChildren = {
  AuthedAdminFramedRouteRoute: AuthedAdminFramedRouteRouteWithChildren,
}

const AuthedAdminRouteRouteWithChildren =
  AuthedAdminRouteRoute._addFileChildren(AuthedAdminRouteRouteChildren)

interface AuthedRouteRouteChildren {
  AuthedAppRouteRoute: typeof AuthedAppRouteRouteWithChildren
  AuthedAdminRouteRoute: typeof AuthedAdminRouteRouteWithChildren
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedAppRouteRoute: AuthedAppRouteRouteWithChildren,
  AuthedAdminRouteRoute: AuthedAdminRouteRouteWithChildren,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

interface authSignInRouteChildren {
  authSignInCallbackRoute: typeof authSignInCallbackRoute
}

const authSignInRouteChildren: authSignInRouteChildren = {
  authSignInCallbackRoute: authSignInCallbackRoute,
}

const authSignInRouteWithChildren = authSignInRoute._addFileChildren(
  authSignInRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  ErrorRoute: ErrorRoute,
  authSignInRoute: authSignInRouteWithChildren,
  healthLivezRoute: healthLivezRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
