/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as healthLivezRouteImport } from './routes/(health)/livez'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AppWsWorkspaceIdRouteImport } from './routes/_app/ws/$workspaceId'
import { Route as AppUUserIdRouteImport } from './routes/_app/u/$userId'
import { Route as authSignInCallbackRouteImport } from './routes/(auth)/sign-in.callback'

const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const healthLivezRoute = healthLivezRouteImport.update({
  id: '/(health)/livez',
  path: '/livez',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWsWorkspaceIdRoute = AppWsWorkspaceIdRouteImport.update({
  id: '/ws/$workspaceId',
  path: '/ws/$workspaceId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUUserIdRoute = AppUUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => AppRouteRoute,
} as any)
const authSignInCallbackRoute = authSignInCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => authSignInRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/sign-in': typeof authSignInRouteWithChildren
  '/livez': typeof healthLivezRoute
  '/api/$': typeof ApiSplatRoute
  '/sign-in/callback': typeof authSignInCallbackRoute
  '/u/$userId': typeof AppUUserIdRoute
  '/ws/$workspaceId': typeof AppWsWorkspaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/sign-in': typeof authSignInRouteWithChildren
  '/livez': typeof healthLivezRoute
  '/api/$': typeof ApiSplatRoute
  '/sign-in/callback': typeof authSignInCallbackRoute
  '/u/$userId': typeof AppUUserIdRoute
  '/ws/$workspaceId': typeof AppWsWorkspaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/error': typeof ErrorRoute
  '/(auth)/sign-in': typeof authSignInRouteWithChildren
  '/(health)/livez': typeof healthLivezRoute
  '/api/$': typeof ApiSplatRoute
  '/(auth)/sign-in/callback': typeof authSignInCallbackRoute
  '/_app/u/$userId': typeof AppUUserIdRoute
  '/_app/ws/$workspaceId': typeof AppWsWorkspaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/error'
    | '/sign-in'
    | '/livez'
    | '/api/$'
    | '/sign-in/callback'
    | '/u/$userId'
    | '/ws/$workspaceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/error'
    | '/sign-in'
    | '/livez'
    | '/api/$'
    | '/sign-in/callback'
    | '/u/$userId'
    | '/ws/$workspaceId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/error'
    | '/(auth)/sign-in'
    | '/(health)/livez'
    | '/api/$'
    | '/(auth)/sign-in/callback'
    | '/_app/u/$userId'
    | '/_app/ws/$workspaceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ErrorRoute: typeof ErrorRoute
  authSignInRoute: typeof authSignInRouteWithChildren
  healthLivezRoute: typeof healthLivezRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(health)/livez': {
      id: '/(health)/livez'
      path: '/livez'
      fullPath: '/livez'
      preLoaderRoute: typeof healthLivezRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ws/$workspaceId': {
      id: '/_app/ws/$workspaceId'
      path: '/ws/$workspaceId'
      fullPath: '/ws/$workspaceId'
      preLoaderRoute: typeof AppWsWorkspaceIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/u/$userId': {
      id: '/_app/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof AppUUserIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(auth)/sign-in/callback': {
      id: '/(auth)/sign-in/callback'
      path: '/callback'
      fullPath: '/sign-in/callback'
      preLoaderRoute: typeof authSignInCallbackRouteImport
      parentRoute: typeof authSignInRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppUUserIdRoute: typeof AppUUserIdRoute
  AppWsWorkspaceIdRoute: typeof AppWsWorkspaceIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppUUserIdRoute: AppUUserIdRoute,
  AppWsWorkspaceIdRoute: AppWsWorkspaceIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface authSignInRouteChildren {
  authSignInCallbackRoute: typeof authSignInCallbackRoute
}

const authSignInRouteChildren: authSignInRouteChildren = {
  authSignInCallbackRoute: authSignInCallbackRoute,
}

const authSignInRouteWithChildren = authSignInRoute._addFileChildren(
  authSignInRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ErrorRoute: ErrorRoute,
  authSignInRoute: authSignInRouteWithChildren,
  healthLivezRoute: healthLivezRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
